// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dal "gately/internal/dal"

	mock "github.com/stretchr/testify/mock"
)

// UrlStoreOption is an autogenerated mock type for the UrlStoreOption type
type UrlStoreOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: store
func (_m *UrlStoreOption) Execute(store *dal.MongoUrlStore) {
	_m.Called(store)
}

type mockConstructorTestingTNewUrlStoreOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewUrlStoreOption creates a new instance of UrlStoreOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUrlStoreOption(t mockConstructorTestingTNewUrlStoreOption) *UrlStoreOption {
	mock := &UrlStoreOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
