// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	dal "gately/internal/dal"

	mock "github.com/stretchr/testify/mock"
)

// UrlShortener is an autogenerated mock type for the UrlShortener type
type UrlShortener struct {
	mock.Mock
}

// CheckAndSanitizeUrl provides a mock function with given fields: longUrl
func (_m *UrlShortener) CheckAndSanitizeUrl(longUrl string) (string, bool) {
	ret := _m.Called(longUrl)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(longUrl)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(longUrl)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// CreateUrlMapping provides a mock function with given fields: ctx, url
func (_m *UrlShortener) CreateUrlMapping(ctx context.Context, url string) (string, error) {
	ret := _m.Called(ctx, url)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUrlMapping provides a mock function with given fields: ctx, url
func (_m *UrlShortener) DeleteUrlMapping(ctx context.Context, url string) error {
	ret := _m.Called(ctx, url)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUrlMetrics provides a mock function with given fields: ctx, start, end, asc
func (_m *UrlShortener) GetUrlMetrics(ctx context.Context, start int64, end int64, asc bool) ([]*dal.UrlMappingEntry, error) {
	ret := _m.Called(ctx, start, end, asc)

	var r0 []*dal.UrlMappingEntry
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, bool) []*dal.UrlMappingEntry); ok {
		r0 = rf(ctx, start, end, asc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dal.UrlMappingEntry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, bool) error); ok {
		r1 = rf(ctx, start, end, asc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RedirectUrl provides a mock function with given fields: ctx, shortUrl
func (_m *UrlShortener) RedirectUrl(ctx context.Context, shortUrl string) (string, error) {
	ret := _m.Called(ctx, shortUrl)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortUrl)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUrlShortener interface {
	mock.TestingT
	Cleanup(func())
}

// NewUrlShortener creates a new instance of UrlShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUrlShortener(t mockConstructorTestingTNewUrlShortener) *UrlShortener {
	mock := &UrlShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
